(()=>{const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];$$('[data-year]').forEach(n=>n.textContent=new Date().getFullYear());
const menu=$('.mobile-nav'),open=$('.burger'),close=$('.mobile-close');
function menuState(on){menu?.classList.toggle('open',on);document.body.style.overflow=on?'hidden':'';open?.setAttribute('aria-expanded',String(on))}
open?.setAttribute('aria-expanded','false');open?.addEventListener('click',()=>menuState(true));close?.addEventListener('click',()=>menuState(false));$$('.mobile-nav a').forEach(a=>a.addEventListener('click',()=>menuState(false)));document.addEventListener('keydown',e=>{if(e.key==='Escape')menuState(false)});
const items=$$('.catalog-card'),filters=$$('.catalog-filters button');
filters.forEach(b=>b.addEventListener('click',()=>{filters.forEach(f=>{f.classList.toggle('active',f===b);f.setAttribute('aria-pressed',String(f===b))});items.forEach((card,i)=>{const show=b.dataset.filter==='all'||card.dataset.category===b.dataset.filter;card.hidden=!show;if(show){card.classList.remove('card-enter');void card.offsetWidth;card.classList.add('card-enter')}})}));
const form=$('#message-form');form?.addEventListener('submit',e=>{e.preventDefault();const name=$('#sender-name')?.value.trim()||'',contact=$('#sender-contact')?.value.trim()||'',message=$('#sender-message')?.value.trim()||'';const text=['Здравствуйте, Кристина! Меня зовут '+name+'.',contact?'Как со мной связаться: '+contact:'','Хочу обсудить макияж/образ: '+message].filter(Boolean).join('\n\n');window.open('https://t.me/share/url?url='+encodeURIComponent('https://t.me/anisimova_65')+'&text='+encodeURIComponent(text),'_blank','noopener,noreferrer')});
const motionTargets=$$('main section, .intro-copy, .catalog-card, .contact-layout>div, .contact-image, .booking-link');motionTargets.forEach((el,i)=>{el.classList.add('motion-item');el.style.setProperty('--motion-delay',Math.min(i%6,5)*70+'ms')});
if('IntersectionObserver'in window&&!matchMedia('(prefers-reduced-motion: reduce)').matches){document.documentElement.classList.add('motion-enabled');const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');io.unobserve(e.target)}}),{threshold:.08,rootMargin:'0px 0px -35px 0px'});motionTargets.forEach(el=>io.observe(el))}else motionTargets.forEach(el=>el.classList.add('in-view'));
})();